### ISSUE TITLE
not responding

### ISSUE THREAD

**Issue by fariqsalafy** [LineageOS-MediaTek/android_device_motorola_nicklaus#1]
i tried this rom. it's good. but it suddenly restart when i open file manager or when i use google launcher. and some time when the phone work hard. any solution?

**Comment by SamarV-121** [comment]
which build you used ? 
link me that build

**Comment by fariqsalafy** [comment]
Xt1770

**Comment by SamarV-121** [comment]
give me link of that rom

**Comment by fariqsalafy** [comment]
Moto E4 Plus ( Mediatek Varient )

# Guides
Unlocking Bootloader:
* Download ADB tool: https://goo.gl/7Y6XVn
* Extract and go in ADB tool's folder then press shift with right click and
click on open command window here
* then type adb devices
* adb reboot bootloader
* fastboot oem unlock
* fastboot reboot

Flashing Recovery (TWRP)
* copy recovery.img (TWRP) in ADB tool folder
* adb reboot bootloader
* fastboot erase recovery
* fastboot flash recovery recovery.img
* fastboot boot recovery.img

Flashing Custom Rom:
* Boot into recovery
* Wipe data,system,boot,cache,dalvic cache
* Then navigate rom's zip and flash it
* Flash gapps ( https://www.opengapps.org ) [OPTIONAL]
* Reboot

# Stock Firmware
* https://firmwareos.com/download-motorola-moto-e4-plus-xt1770-firmware

# Recovery
[TWRP][OFFICIAL][STABLE] TWRP-3.2.1: https://goo.gl/61YH16

# Roms
Nougat:
[7.2.1][STABLE] LineageOS-14.1: https://goo.gl/qyhMGy
[7.2.1][STABLE] RessurectionRemix-5.8.5:
https://samarv-121.blogspot.in/2018/05/rom712unofficialstablenicklaus.html
[7.2.1][STABLE] DotOS-1.2:
https://drive.google.com/file/d/14W_yZECcu1t_WsIH5ciSKpBYvVnrS7ot/view?usp=sharing
Oreo:
[8.1.1][ALPHA] RessurectionRemix-5.6.0: https://goo.gl/eXZjzX

# Magisk
* http://tiny.cc/latestmagisk

# Facebook Group: https://goo.gl/xKtLdB

# Source Codes
* Device Tree:
https://github.com/LineageOS-MediaTek/android_device_motorola_nicklaus
* Common Tree:
https://github.com/LineageOS-MediaTek/android_device_mediatek_mt6737-common
* Vendor Tree:
https://github.com/LineageOS-MediaTek/proprietary_vendor_motorola
* Kernel Source:
https://github.com/SamarV-121/android_kernel_motorola_nicklaus

**Comment by SamarV-121** [comment]
;______;
[7.2.1][STABLE] LineageOS-14.1: https://goo.gl/qyhMGy
[7.2.1][STABLE] RessurectionRemix-5.8.5:
https://samarv-121.blogspot.in/2018/05/rom712unofficialstablenicklaus.html
[7.2.1][STABLE] DotOS-1.2:
https://drive.google.com/file/d/14W_yZECcu1t_WsIH5ciSKpBYvVnrS7ot/view?usp=sharing
Oreo:
[8.1.1][ALPHA] RessurectionRemix-5.6.0: https://goo.gl/eXZjzX


you faced that issue on which rom ?

**Comment by fariqsalafy** [comment]
Rr by samar, android n.

**Comment by SamarV-121** [comment]
Provide me logcat
